# Generated by Django 3.2.8 on 2021-10-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
